on:
  schedule:
    # Every day at 9:30 UTC/5:30 ET
    - cron:  '30 9 * 1,2,9-12 *'
    # TNF 6:00 AM UTC / 1:00 AM ET
    - cron:  '0 6 * 1,2,9-12 5'
    # Early window: 10:30 PM UTC / 5:30 PM ET
    - cron:  '30 22 * 1,2,9-12 0'
    # Late window: 0:30 UTC / 8:30 ET
    - cron:  '30 0 * 1,2,9-12 1'
    # SNF/MNF: 6:00 UTC / 1:00 ET
    - cron:  '00 6 * 1,2,9-12 1'
    - cron:  '00 6 * 1,2,9-12 2'
  workflow_dispatch:
  
jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::nflreadr

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        run: Rscript -e 'source("nfl_schedule.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          # git add schedule_test.csv
          git add *
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
